apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
  labels:
    app: postgres
    component: storage
    app.kubernetes.io/part-of: pasb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  selector:
    matchLabels:
      app: postgres
      component: storage
      storage-type: hostpath
  resources:
    requests:
      storage: 30Gi
