apiVersion: v1
kind: ResourceQuota
metadata:
  name: postgres-resource-quota
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: pasb
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    pods: "4"
