apiVersion: v1
kind: ResourceQuota
metadata:
  name: n8n-quota
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: pasb
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "10"
    persistentvolumeclaims: "3"
