apiVersion: v1
kind: ResourceQuota
metadata:
  name: redis-resource-quota
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: pasb
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    persistentvolumeclaims: "2"
    pods: "4"
