apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: redis
  labels:
    app: redis
    component: storage
    app.kubernetes.io/part-of: pasb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-storage
  selector:
    matchLabels:
      app: redis
      component: storage
      storage-type: hostpath
  resources:
    requests:
      storage: 10Gi
